### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by rex-tseng** [fidelisrafael/ajax-long-polling-chat#1]
I was clone it to my wamp sever's www fold

and rename the db-config-sample to db-config-development.php

and i'm sure i creat database and table 

but when i link to index.php

it got many php error

and ahow"
Please, create the database `DB_NAME` for application.

You can import the file MIGRATIONS_FOLDER/createSimple_chat.sql using phpMyAdmin/mysqldump   or run :

mysql -u [YOU USERNAME] -p[YOUR PASSWORD] < MIGRATIONS_FOLDER/createSimple_chat.sql
Now finish, and create database tables
"

(but i just do that before!!(creat db and table ,check db-config)

could u give me some help?

**Comment by viiter** [comment]
the instructions are wrong, they say that you should have a php file named `db-config-development.php` but the app itself is actually looking for `db-config-production.php` not  sure where to switch between development or production mode but renaminig it to *-production.php worked for me

**Comment by fidelisrafael** [comment]
Hi there, thanks for feedback.

My method of environment validation is very simple(and not super effective), i just check if server host address is 127.0.0.1, if not this will set the env for production.

@ZingYu Can you try again renaming the file to `db-config-production.php`.?

@viiter Thanks for support, i will try to make a better validation for local development env and production env, and update the docs. 

Thanks again!
