### ISSUE TITLE
Not appending new messages

### ISSUE THREAD

**Issue by yourjhay** [fidelisrafael/ajax-long-polling-chat#3]
http://ucctalks.ezyro.com/longchat/

is the url of this ... i try your project and it seems its not appending when i click send .. and also the messages send by others.

**Comment by fidelisrafael** [comment]
Hi @jhayann sorry for delay in replying this. I can't access this URL(403 Forbidden), do you remember the version of php you've tested this?

**Comment by fidelisrafael** [comment]
@jhayann  I'm closing this since theres no response.
