### ISSUE TITLE
unable to connect 

### ISSUE THREAD

**Issue by ghost** [fidelisrafael/ajax-long-polling-chat#4]
Fatal error: Class 'Chat\Database' not found in D:\xampp\htdocs\ajax-long-polling-chat-master\lib\message.php on line 28

**Comment by fidelisrafael** [comment]
Hi @xunny888 what version of PHP are you running? I don't have to much time to maintain this repository...but  I want to help you... In any case, Pull Requests are welcome :)

**Comment by fidelisrafael** [comment]
@xunny888 I'm closing this since theres no response.
